### PR TITLE
chore(deploy): add redirects to netlify file

### PR DESCRIPTION
**Pull request by trybick**
#### Summary

Resolves: 

- Open deployed site, go to d3 route, refresh the page, notice an error.
- Adds a redirect to fix the above issue.
- Reference: https://dev.to/dance2die/page-not-found-on-netlify-with-react-router-58mc

Screen Shot 2020-12-13 at 1 27 54 PM

#### Checklist

- [ ] Branch is in format `TYPE/scope/description`
- [ ] PR title is in semantic format `TYPE(scope): description`
- [ ] Commits Messages are in semantic format `TYPE(scope): description`
- [ ] Has Summary
- [ ] Has Labels

### CODE REVIEW

**Comment by trybick** [comment]
If we want a netlify scope let me know

**Comment by davidholyko** [comment]
I think adding netlify scope makes sense. I think build will be rarely used. I suggest we remove it. This seems like a chore

**Comment by davidholyko** [comment]
Can we remove this as well.

https://github.com/f1v/full-git-commit-history-app/blob/master/.github/semantic.yml#L15

**Review by davidholyko — CHANGES_REQUESTED** [review]
Request: add netlify to commit message scope

**Comment by davidholyko** [comment]
After rebasing or merging with master, this should pass our git check and itll be quick approval

**Review by davidholyko — APPROVED** [review]
LGTM

**Pull request merged**
